"""Spec section: `mvault` Determinism."""

import os
import re
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pytest

from conftest import entry_by_id, payload, read_catalog, run_cli, source_entry

TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$")


def sync_with(vault, source, episodes=(), streams=(), clips=()):
    source.serve(payload(episodes, streams, clips))
    result = run_cli("sync", "demo", cwd=vault.parent)
    assert result.returncode == 0, result.stderr
    return read_catalog(vault)


def all_keys(entry):
    fields = ("title", "description", "views", "likes", "preview", "removed")
    return [key for field in fields for key in entry[field]]


# Determinism: "Datetime text | `YYYY-MM-DDTHH:MM:SS` without timezone suffix"
# — applies to stored `published` values.
@pytest.mark.parametrize(
    "published,expected",
    [
        ("2024-05-06T07:08:09", "2024-05-06T07:08:09"),
        ("2024-05-06T07:08:09Z", "2024-05-06T07:08:09"),
        ("2024-05-06T07:08:09.123456", "2024-05-06T07:08:09"),
        ("2024-05-06T07:08:09+02:00", "2024-05-06T07:08:09"),
        ("2024-05-06 07:08:09", "2024-05-06T07:08:09"),
    ],
    ids=["plain", "zulu", "microseconds", "offset", "space-separator"],
)
def test_published_datetimes_are_normalized(vault, source, published, expected):
    catalog = sync_with(vault, source, episodes=[source_entry("e1", published=published)])
    assert entry_by_id(catalog, "episodes", "e1")["published"] == expected


# Determinism: "Date-only source values | Normalize to `00:00:00` time
# component".
def test_date_only_published_gets_a_midnight_time(vault, source):
    catalog = sync_with(vault, source, episodes=[source_entry("e1", published="2024-05-06")])
    assert entry_by_id(catalog, "episodes", "e1")["published"] == "2024-05-06T00:00:00"


# Determinism: "Entry order | Newest `published` first; ties break by
# lexicographically smaller `id`" — normalization happens before ordering, so
# a date-only value sorts by its midnight form.
def test_normalized_values_drive_ordering(vault, source):
    catalog = sync_with(
        vault,
        source,
        clips=[
            source_entry("dateonly", published="2024-05-06"),
            source_entry("later", published="2024-05-06T01:00:00"),
            source_entry("earlier", published="2024-05-05T23:00:00"),
        ],
    )
    assert [e["id"] for e in catalog["clips"]] == ["later", "dateonly", "earlier"]


# Determinism: "Sync timestamps | Reflect sync execution time" — history keys
# land near the moment the sync ran.
def test_sync_timestamp_reflects_execution_time(vault, source):
    before = datetime.now().replace(microsecond=0)
    catalog = sync_with(vault, source, episodes=[source_entry("e1")])
    after = datetime.now().replace(microsecond=0) + timedelta(seconds=2)

    key = max(entry_by_id(catalog, "episodes", "e1")["title"])
    assert before - timedelta(seconds=1) <= datetime.fromisoformat(key) <= after


# Determinism: "Sync timestamps | ... remain strictly increasing whenever new
# history entries are appended" — across several rapid syncs.
def test_sync_timestamps_strictly_increase(vault, source):
    for views in (1, 2, 3, 4):
        catalog = sync_with(vault, source, episodes=[source_entry("e1", views=views)])

    keys = list(entry_by_id(catalog, "episodes", "e1")["views"])
    assert len(keys) == 4
    assert len(set(keys)) == 4  # each sync appended at its own, strictly later second


# Determinism: "Sync timestamps ... strictly increasing" — keys never collide
# across different fields or entries of the same vault.
def test_timestamps_across_entries_never_go_backwards(vault, source):
    sync_with(vault, source, episodes=[source_entry("e1", views=1)])
    catalog = sync_with(
        vault,
        source,
        episodes=[source_entry("e1", views=2), source_entry("e2")],
    )

    first_keys = all_keys(entry_by_id(catalog, "episodes", "e1"))
    second_entry_keys = all_keys(entry_by_id(catalog, "episodes", "e2"))
    assert min(second_entry_keys) > min(first_keys)


# Determinism: "Datetime text | `YYYY-MM-DDTHH:MM:SS` without timezone suffix"
# — every history key generated by sync uses that exact shape.
def test_all_generated_keys_use_the_documented_shape(vault, source):
    sync_with(vault, source, episodes=[source_entry("e1", views=1)])
    catalog = sync_with(vault, source, episodes=[source_entry("e1", views=2)])

    for key in all_keys(entry_by_id(catalog, "episodes", "e1")):
        assert TIMESTAMP.match(key), key


# Determinism: "Locale | No locale-sensitive formatting anywhere" — output is
# identical under a non-default locale environment.
def test_output_is_locale_independent(tmp_path, source):
    mvault = str(Path(__file__).resolve().parents[1] / "mvault.py")
    source.serve(payload(episodes=[source_entry("e1", published="2024-05-06")]))
    env = dict(os.environ, LC_ALL="C", LANG="C")

    for name in ("a", "b"):
        subprocess.run([sys.executable, mvault, "init", name, source.url], cwd=tmp_path, env=env)
        subprocess.run([sys.executable, mvault, "sync", name], cwd=tmp_path, env=env)

    first = read_catalog(tmp_path / "a")["episodes"][0]
    second = read_catalog(tmp_path / "b")["episodes"][0]
    assert first["published"] == second["published"] == "2024-05-06T00:00:00"
